@startuml


autonumber
actor Client as cl
participant API_CFPS as api1
participant CFPS
participant API_Bank as api2
participant Bank
participant Bank_corr as cor
database CFPS_DB as db1
database Bank_DB as db2




cl -> api1: Request: \n*login \n*PIN \n*Card_info \n*Amount \n*Payment receiver
api1 --> CFPS:
CFPS->CFPS
CFPS -> api2: Request: \n*Card_info \n*Amount \n*Payment receiver
api2 --> Bank:
Bank->Bank
cor<->Bank: \n*Amount \n*Transaction status
Bank->Bank
Bank->CFPS:Response: \n*Transaction status
CFPS->CFPS
CFPS->cl:Response: \n*Transaction status
CFPS<-->db1:Read/Record
Bank<-->db2:Read/Record
@enduml